apiVersion: v1
kind: Service
metadata:
  labels:
    env: $ENV
    component: $COMPONENT
    role: $ROLE
  name: $SERVICE_NAME
  namespace: default
spec:
  selector:
    env: $ENV
    color: $COLOR
    component: $COMPONENT
    role: $ROLE
  ports:
  - port: $SERVICE_PORT
    targetPort: $CONTAINER_PORT
    name: http
